language: bash
services: docker

env:
  - VERSION=5.0
  - VERSION=5.0/alpine
  - VERSION=2.4
  - VERSION=2.3
  - VERSION=2.3/alpine
  - VERSION=2.2
  - VERSION=2.2/alpine
  - VERSION=2.1
  - VERSION=2.1/alpine
  - VERSION=2.0
  - VERSION=2.0/alpine
  - VERSION=1.5
  - VERSION=1.5/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="logstash:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
